export { default as Navigation } from './Navigation/Navigation'
export { default as Hero } from './Hero/Hero'
export { default as Appointment } from './Appointment/Appointment'
export { default as Footer } from './Footer/Footer'
export { default as ElaClinicCta } from './ElaClinicCta/ElaClinicCta'
