import type { NextPage } from 'next'
import Head from 'next/head'

import { Navigation, Hero, Appointment, Footer, ElaClinicCta } from '@features'
import { RegainYourHealth, Benefits, Steps } from '@/features/Sections'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navigation />
      <Hero />
      <main>
        <RegainYourHealth />
        <Benefits />
        <Steps />
        <Appointment />
        <ElaClinicCta />
      </main>
      <Footer />
    </>
  )
}

export default Home
