import type { NextPage } from 'next'
import Head from 'next/head'

import { Container } from '@atoms'
import { Navigation, Hero } from '@features'
import { RegainYourHealth, Benefits, Steps } from '@/features/Sections'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navigation />
      <Hero />
      <main>
        <RegainYourHealth />
        <Benefits />
        <Steps />
      </main>
      <Container className="test">
        <div className="mt-96 pt-96" id="programare">
          test
        </div>
      </Container>
    </>
  )
}

export default Home
