import type { NextPage } from 'next'
import Head from 'next/head'

import { ElaImage, FancyTitle, Container } from '@atoms'
import { Navigation, Hero } from '@/features'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navigation />
      <Hero />
      <Container className="test">
        <div className="mt-96 pt-96" id="programare">
          test
        </div>
      </Container>
    </>
  )
}

export default Home
